name: Vue

on:
  push:
    branches: [ master ]  

jobs:
  vue-unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      working-directory: ./vue3
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'

    - name: Copy .env
      working-directory: ./vue3
      run: cp .env.example .env
      env:
        VUE_APP_API_URL: http://localhost:8000/api

    - name: Run Unit Testing
      working-directory: ./vue3
      run: npm run test:unit